sequenceDiagram
  participant participant_isCapabilityCatalog as isCapabilityCatalog
  participant participant_parseCapabilityCatalog as parseCapabilityCatalog
  participant_isCapabilityCatalog->>participant_parseCapabilityCatalog: parseCapabilityCatalog()
  participant_parseCapabilityCatalog-->>participant_isCapabilityCatalog: return
