sequenceDiagram
  participant participant_normalizeCapability as normalizeCapability
  participant participant_uniqueSortedStrings as uniqueSortedStrings
  participant_normalizeCapability->>participant_uniqueSortedStrings: uniqueSortedStrings()
  participant_uniqueSortedStrings-->>participant_normalizeCapability: return
